services:
  panel:
    image: ghcr.io/pterodactyl/panel
    container_name: pterodactyl_panel
    restart: unless-stopped
    depends_on:
      - db
      - cache
    networks:
      - pterodactyl
    ports:
      - 8080:80
    environment:
      APP_URL: ${PANEL_URL}
      APP_TIMEZONE: ${TIMEZONE}
      APP_SERVICE_AUTHOR: ${PANEL_SERVICE_AUTHOR}
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: false
      TRUSTED_PROXIES: ${PANEL_TRUSTED_PROXIES}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: cache
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
    volumes:
      - ./panel/var:/app/var
      - ./panel/logs:/app/storage/logs

  db:
    image: mariadb:10.5
    container_name: pterodactyl_db
    restart: unless-stopped
    networks:
      - pterodactyl
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./panel/db:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: unless-stopped
    networks:
      - pterodactyl

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    networks:
      - pterodactyl
    ports:
      - 8443:443
      - 2022:2022
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./wings/config:/etc/pterodactyl
      - ./wings/data:/var/lib/pterodactyl
      - ./wings/logs:/var/log/pterodactyl
      - /var/lib/pterodactyl:/var/lib/pterodactyl
      - /tmp/pterodactyl/:/tmp/pterodactyl

networks:
  pterodactyl:
    name: pterodactyl_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
